# Generated by Django 3.2.5 on 2022-11-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='cities',
            new_name='city_region',
        ),
    ]
